(include_subdirs qualified)

(library
 (name monad_lib)
 (public_name monad-spec.monad_lib)
 (libraries zarith lens digestif ctypes ctypes.stubs ctypes-foreign)
 (preprocess
  (pps lens.ppx_deriving)))

(env
 (release
  (ocamlopt_flags
   (:standard -unsafe -noassert -inlining-report -inline 100 -O3 -w -64-55))))
