open Monad_lib
open Byte_string
open Test_utils.Utils
open QCheck2

module Nibbles = Mpt.Nibbles

let gen_nibble : char Gen.t = Gen.(char_range '\x00' '\x0f')
let gen_nibbles : Nibbles.t Gen.t = Gen.(map Nibbles.of_nibble_array (small_string ~gen:gen_nibble))

let round_trip_hp_ok ((nibbles, flag) : Nibbles.t * bool) =
  let hp = Nibbles.hex_prefix_encode nibbles flag in
  let nibbles', flag' = Nibbles.hex_prefix_decode hp in
  Nibbles.(nibbles = nibbles') && flag = flag'

type operation = Add of {key : Bytes.t; value : Bytes.t} | Remove of {key : Bytes.t} | Merkleize
let gen_operation possible_keys =
  Gen.(
    let gen_key = oneofl possible_keys in
    let gen_add =
      let* key = gen_key in
      let* value = string ~nonempty:false in
      return (Add {key; value})
    in
    let gen_remove =
      let* key = gen_key in
      return (Remove {key})
    in
    let gen_merkleize = return Merkleize in
    frequency [(10, gen_add); (10, gen_remove); (1, gen_merkleize)] )

let print_operation = function
  | Merkleize -> "Merkleize"
  | Add {key; value} ->
      Format.sprintf "Add { key = \"%s\"; value = \"%s\" }" (Bytes.to_hex_string key)
        (Bytes.to_hex_string value)
  | Remove {key} -> Format.sprintf "Remove { key = \"%s\" }" (Bytes.to_hex_string key)

let gen_key =
  Gen.(
    (* Keys are generated by picking one of three possible nibbles, to ensure they overlap. *)
    let gen_nibble_pair = oneofl ['\xaa'; '\xab'; '\xac'; '\xba'; '\xbb'; '\xbc'; '\xca'; '\xcb'; '\xcc'] in
    string_of ~nonempty:true gen_nibble_pair )
let gen_key_set = Gen.(list_size (1 -- 100) gen_key)

let gen_run =
  Gen.(
    let* key_set = gen_key_set in
    list_size (1 -- 100) (gen_operation key_set) )

let print_run = Print.list print_operation

module Mpt_byte_map =
  Mpt.Make
    (struct
      let hash_keys = false
    end)
    (struct
      include Bytes
      let to_bytes = Fun.id
    end)
    (struct
      include Bytes
      let to_bytes = Fun.id
      let commit = Fun.id
    end)

(* TODO: better fuzzing would be ideal. This just checks that MPTs are well-behaved with respect to
   map operations, and that their Merkle roots are consistent. We would also like to compare the Merkle
   roots against a reference version. *)
let rec check_invariants ({data; _} : 'a Mpt.Generic.t) : bool =
  (* Check structural invariants. *)
  match data with
  | Empty -> true
  | Branch (branches, value) ->
      (* Check that there are enough non-empty branches to justify not compressing. *)
      let non_empty =
        (* Non-empty branches plus value if present. *)
        (if Option.is_some value then 1 else 0)
        + ( Iarray.to_seq branches
          |> Seq.filter (function Mpt.Generic.{data = Empty; _} -> false | _ -> true)
          |> Seq.length )
      in
      non_empty > 1 && Iarray.for_all check_invariants branches
  | Extension {ending = Subtree {data = Extension _; _}; _} ->
      (* Should have been compressed to a single Extension. *)
      false
  | Extension {ending = Subtree {data = Empty; _}; _} ->
      (* Should have been compressed to Empty. *)
      false
  | Extension {ending = Subtree st; path} ->
      (* If path was empty, this node should've been replaced by st. *)
      Nibbles.(path <> empty) && check_invariants st
  | Extension {ending = Value _; _} -> true

let run_ok (run : operation list) =
  (* Apply a run in parallel to all three kinds of maps, check results. *)
  let apply_operation (map, mpt_generic, mpt_map) = function
    | Merkleize ->
        let mpt_generic = Mpt.Generic.merkleized ~value_to_bytes:Fun.id mpt_generic in
        let mpt_map = Mpt_byte_map.merkleized mpt_map in
        (map, mpt_generic, mpt_map)
    | Add {key; value} ->
        let map = Bytes.Map.add key value map in
        let mpt_generic = Mpt.Generic.add key value mpt_generic in
        let mpt_map = Mpt_byte_map.add key value mpt_map in
        (map, mpt_generic, mpt_map)
    | Remove {key} ->
        let map = Bytes.Map.remove key map in
        let mpt_generic = Mpt.Generic.remove key mpt_generic in
        let mpt_map = Mpt_byte_map.remove key mpt_map in
        (map, mpt_generic, mpt_map)
  in
  let map, mpt_generic, mpt_map =
    List.fold_left apply_operation (Bytes.Map.empty, Mpt.Generic.empty, Mpt_byte_map.empty) run
  in
  let check_entries entries = Bytes.Map.equal Bytes.equal map (Bytes.Map.of_seq entries) in
  let same_merkle_root =
    B32.(
      Mpt.Generic.(merkle_root (merkleized ~value_to_bytes:Fun.id mpt_generic))
      = Mpt_byte_map.(merkle_root (merkleized mpt_map)) )
  in
  same_merkle_root
  && check_invariants mpt_generic
  && check_invariants mpt_map.mpt
  && check_entries (Mpt.Generic.to_seq mpt_generic)
  && check_entries (Mpt_byte_map.to_seq mpt_map)

let test_case_of_fixture (name, fixture) =
  let open Fixtures.TrieTest in
  let trie =
    List.fold_left
      (fun trie (k, v) -> if Bytes.(v = empty) then Mpt.Generic.remove k trie else Mpt.Generic.add k v trie)
      Mpt.Generic.empty fixture.entries
    |> Mpt.Generic.merkleized ~value_to_bytes:Fun.id
  in
  let root' = Mpt.Generic.merkle_root trie in
  Alcotest.(test_case name `Quick (fun () -> check' b32 ~msg:"Root" ~expected:fixture.root ~actual:root'))

let test_fixture_file ?(hash_keys = false) file =
  (* TODO: do something disciplined about paths *)
  let path = "../../../../third_party/tests/TrieTests/" ^ file in
  let test_fixtures =
    Result.get_ok (Fixtures.TrieTest.of_yojson ~hash_keys (Yojson.Safe.from_file ~fname:file path))
  in
  (file, List.map test_case_of_fixture test_fixtures)

let () =
  let open Alcotest in
  run "Tests on MPT data structures"
    [ ( "Hex-prefix round-trip"
      , [ check_prop
            ~print:Print.(pair Nibbles.to_hex_string bool)
            ~name:"round_trip_hp_ok ns"
            Gen.(pair gen_nibbles bool)
            round_trip_hp_ok ] )
    ; ("Map fuzzing", [check_prop ~count:10_000 ~print:print_run ~name:"run_ok" gen_run run_ok])
    ; test_fixture_file ~hash_keys:true "hex_encoded_securetrie_test.json"
    ; test_fixture_file ~hash_keys:true "trietest_secureTrie.json"
    ; test_fixture_file ~hash_keys:true "trieanyorder_secureTrie.json"
    ; test_fixture_file "trietest.json"
    ; test_fixture_file "trieanyorder.json" ]
