name Code Quality Checks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  formatting-check:
    name: Check ocamlformat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.4.0

      - name: Install ocamlformat
        run: |
          opam install ocamlformat.0.28.1

      - name: Run ocamlformat
        run: |
          opam exec -- dune build @fmt --pkg=disabled
