name: Tests

on:
  push:

jobs:
  test:
    name: Dune tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: true

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ocaml-variants.5.4.0+options,ocaml-option-flambda

      - name: Install dependencies
        run: |
          opam install . --deps-only -y

      - name: Build
        run: |
          opam exec -- dune build --verbose

      - name: Fetch external test fixtures
        run: |
          ./scripts/download_mf_tests.sh

      - name: Run tests
        run: |
          opam exec -- dune runtest --verbose
